import streamlit as st
import os
from groq import Groq
import pandas as pd

# =========================
# REPORT CARD PAGE
# =========================
st.title("📄 Report Card Generator")

# Subject list
subjects = ["Maths", "Science", "SST", "Hindi", "English", "3rd Language"]

# Initialize session state if needed
if "term1_marks" not in st.session_state:
    st.session_state.term1_marks = [0, 0, 0, 0, 0, 0]

if "term2_marks" not in st.session_state:
    st.session_state.term2_marks = [0, 0, 0, 0, 0, 0]

if "student_details" not in st.session_state:
    st.session_state.student_details = None


# =========================
# GROQ AI FUNCTION
# =========================
def ask_groq(prompt):
    try:
        GROQ_API_KEY = os.getenv("GROQ_API_KEY")
        api_key = GROQ_API_KEY
        if not api_key:
            return "Groq API key not set."

        client = Groq(api_key=api_key)
        message = client.chat.completions.create(
            messages=[
                {"role": "user", "content": prompt}
            ],
            model="llama-3.1-8b-instant",
        )
        return message.choices[0].message.content

    except Exception as e:
        return f"AI service is currently unavailable: {str(e)}"


# =========================
# REPORT CARD LOGIC
# =========================
def generate_report(marks):
    total = sum(marks)
    percentage = (total / (len(marks) * 100)) * 100  # Calculate percentage out of total

    if percentage >= 90:
        grade = "A"
    elif percentage >= 75:
        grade = "B"
    elif percentage >= 50:
        grade = "C"
    else:
        grade = "D"

    return total, percentage, grade


# =========================
# STUDENT DETAILS FORM
# =========================
st.header("👤 Student Details")

with st.form("student_form"):
    col1, col2 = st.columns(2)
    
    with col1:
        name = st.text_input("Student Name", value=st.session_state.student_details["name"] if st.session_state.student_details else "")
        age = st.number_input("Age", 1, 100, value=st.session_state.student_details["age"] if st.session_state.student_details else 14)
        gender = st.radio("Gender", ["Male", "Female"])
    
    with col2:
        student_class = st.number_input("Class", 1, 12, value=st.session_state.student_details["class"] if st.session_state.student_details else 1)
        email = st.text_input("Email", value=st.session_state.student_details["email"] if st.session_state.student_details else "")
    save_details = st.form_submit_button("Save Details")

if save_details and name:
    st.session_state.student_details = {
        "name": name,
        "age": age,
        "class": student_class,
        "gender": gender,
        "email": email,
    }
    st.success("✅ Student details saved!")


# =========================
# REPORT CARD GENERATION
# =========================
st.divider()
st.header("📋 Generate Report Card")

col1, col2 = st.columns(2)

with col1:
    if st.button("Generate Term 1 Report", use_container_width=True):
        if not st.session_state.student_details:
            st.error("❌ Please save student details first!")
        elif not any(st.session_state.term1_marks):
            st.error("❌ Please enter Term 1 marks first!")
        else:
            total, percent, grade = generate_report(st.session_state.term1_marks)

            remarks = ask_groq(
                f"Write positive and constructive remarks for a student who scored {percent:.2f}%. Keep it brief (2-3 sentences).And these are the marks: {st.session_state.term1_marks}"
            )

            report_text = f"""
{'='*50}
STUDENT REPORT CARD – TERM 1
{'='*50}

Name: {st.session_state.student_details['name']}
Class: {st.session_state.student_details['class']}
Age: {st.session_state.student_details['age']}
Gender: {st.session_state.student_details['gender']}
Email: {st.session_state.student_details['email']}
{'-'*50}
MARKS BREAKDOWN
{'-'*50}
"""
            
            for i, subject in enumerate(subjects):
                report_text += f"{subject}: {st.session_state.term1_marks[i]}/100\n"
            
            report_text += f"""
{'-'*50}
PERFORMANCE SUMMARY
{'-'*50}
Total Marks: {total}/{len(subjects)*100}
Percentage: {percent:.2f}%
Grade: {grade}

{'-'*50}
REMARKS
{'-'*50}
{remarks}


{'-'*50}
Generated by SYNAPSE - Student Performance System
{'-'*50}
"""

            st.text(report_text)

            st.download_button(
                "📥 Download Term 1 Report",
                report_text,
                file_name="term1_report.txt",
                use_container_width=True
            )

with col2:
    if st.button("Generate Term 2 Report", use_container_width=True):
        if not st.session_state.student_details:
            st.error("❌ Please save student details first!")
        elif not any(st.session_state.term2_marks):
            st.error("❌ Please enter Term 2 marks first!")
        else:
            total, percent, grade = generate_report(st.session_state.term2_marks)

            remarks = ask_groq(
                f"Write positive and constructive remarks for a student who scored {percent:.2f}%. Keep it brief (2-3 sentences).And these are the marks: {st.session_state.term2_marks}"
            )

            report_text = f"""
{'-'*50}
STUDENT REPORT CARD – TERM 2
{'-'*50}

Name: {st.session_state.student_details['name']}
Class: {st.session_state.student_details['class']}
Age: {st.session_state.student_details['age']}
Gender: {st.session_state.student_details['gender']}
Email: {st.session_state.student_details['email']}

{'-'*50}
MARKS BREAKDOWN
{'-'*50}
"""
            
            for i, subject in enumerate(subjects):
                report_text += f"{subject}: {st.session_state.term2_marks[i]}/100\n"
            
            report_text += f"""
{'-'*50}
PERFORMANCE SUMMARY
{'-'*50}
Total Marks: {total}/{len(subjects)*100}
Percentage: {percent:.2f}%
Grade: {grade}

{'-'*50}
REMARKS
{'-'*50}
{remarks}

{'-'*50}
Generated by SYNAPSE - Student Performance System
{'-'*50}
"""

            st.text(report_text)

            st.download_button(
                "📥 Download Term 2 Report",
                report_text,
                file_name="term2_report.txt",
                use_container_width=True
            )


# =========================
# SIDEBAR NAVIGATION
# =========================
st.sidebar.markdown("## 📚 SYNAPSE")
st.sidebar.markdown("Smart Student Dashboard")

